name: Test Kaggle Script Action

on:
  pull_request:
  workflow_dispatch:

jobs:
  test_kaggle_script_action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Kaggle Script Action
        uses: ./.github/actions/kaggle-action
        with:
          username: ${{ secrets.KAGGLE_USERNAME }}
          key: ${{ secrets.KAGGLE_KEY }}
          title: "Test Kaggle Script Action"
          custom_script: |
            !pip install requests
            import requests
            import json
            
            url = 'https://api.open-meteo.com/v1/forecast?latitude=-1.29&longitude=36.82&current_weather=true'
            print(f'Making request to: {url}')
            response = requests.get(url)
            print(f'Status code: {response.status_code}')
            
            if response.status_code == 200:
                data = response.json()
                print('Response data:')
                print(json.dumps(data, indent=2))
            else:
                print(f'Error: {response.text}')
          enable_internet: "true"
          enable_gpu: "true"
          enable_tpu: "false"
          sleep_time: "10"