name: Test Kaggle Script Action

on:
  pull_request:
  workflow_dispatch:

jobs:
  test_kaggle_script_action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy test script directory to root
        run: |
          cp -r tests/ .

      - name: Run Kaggle Script Action
        uses: ./.github/actions/kaggle-action
        with:
          username: ${{ secrets.KAGGLE_USERNAME }}
          key: ${{ secrets.KAGGLE_KEY }}
          title: "Test Kaggle Script Action"
          custom_script: |
            !pip install requests  
            !python tests/test.py --url "https://api.open-meteo.com/v1/forecast?latitude=-1.29&longitude=36.82&current_weather=true "
          enable_internet: "true"
          enable_gpu: "true"
          enable_tpu: "false"
          sleep_time: "10"